Feature/issues/#1
miu-ikeuchi/nyapple pull request #2
Opened 2021-07-26 11:24 UTC by miu-ikeuchi

#1 確認よろしくおねがいします！

2021-07-26 12:53 UTC, kazu-taka requested changes
@miu-ikeuchi 
ほとんどのテーブルを作成するスクリプトができていないようなので確認お願いします！
プッシュし忘れですかね！？😊

2021-07-26 12:53 UTC, kazu-taka commented on README.md
> +-----------------------------
@miu-ikeuchi 
マークダウンの場合、見出しや本文等の前後に空行を入れた方がいいので、以下のように修正お願いします！

```md
-----------------------------

  # アプリ名

  ニャップル

  ## アプリの概要

  保護猫と里親をつなぐマッチングアプリです。

----------------------------- 
```

2021-07-26 12:53 UTC, kazu-taka commented on README.md
> +);
@miu-ikeuchi 
create_userというテーブル名ではなく、ここはusersという名前の方がいいと思います！
また、Googleスプレッドに記載している内容のテーブルが全てスクリプト内に記述されていないので、記述するようにお願いします:bow:
https://docs.google.com/spreadsheets/d/1IB44e1SxdnoIFyiWCaUrUCCRPTNmaT2bZYQ021Md3ls/edit#gid=264027466

2021-07-26 13:56 UTC, kazu-taka requested changes
@miu-ikeuchi 
コメントしたので確認お願いします:bow:

2021-07-26 13:56 UTC, kazu-taka commented on README.md
> +    prefect_id INT(2),
@miu-ikeuchi 
INT型の時は桁数の指定は不要になります！
スプレッドシートの方もINTはTNYINTは桁数不要ですので、削除お願いします!!
prefect_idはprefecturesテーブルのidになるので、prefecture_idにした方がいいと思います！
また、prefecture_idは外部キーになるので、FOREIGN KEYの指定をお願いします✨

2021-07-26 13:56 UTC, kazu-taka commented on README.md
> +    type TINYINT(1) NOT NULL,
@miu-ikeuchi 
ここも桁数の指定は不要です！
他の部分についても、INTやTNYINTの桁数指定は削除お願いします:bow:

2021-07-26 13:56 UTC, kazu-taka commented on README.md
> +    matching_id INT NOT NULL,
@miu-ikeuchi 
matching_idも外部キーとなるため、FOREIGN KEYの指定をお願いします！！

2021-07-26 13:56 UTC, kazu-taka commented on README.md
> +    prefecture VARCHAR(20) NOT NULL,
@miu-ikeuchi 
都道府県テーブルのそれぞれの名称がセットされるので、nameカラムでもいいのかなと思ってました✨

2021-07-26 13:56 UTC, kazu-taka commented on README.md
> +
@miu-ikeuchi 
都道府県テーブルは47都道府県固定なので、ここに47都道府県分のINSERT文を書いておいた方がいいです✨

2021-07-26 22:18 UTC, kazu-taka requested changes
@miu-ikeuchi 
確認漏れ等があったので、再度コメントしました:bow:
修正お願いします！！

2021-07-26 22:18 UTC, kazu-taka commented on README.md
> +CREATE USER users IDENTIFIED BY "1234";
@miu-ikeuchi 
前回気が付かなかったのですが、ここはusersではなくnyapple_userとかnyapple_adminとかの方がいいですね！
今更ですがにゃっぷるってかわいいですね笑

2021-07-26 22:18 UTC, kazu-taka commented on README.md
> +    prefecturesecture_id INT,
@miu-ikeuchi 
prefecturesテーブルの外部キーになるので、prefecture_idの方がいいですね！
FOREIGN KEYの部分も見直しお願いします:bow:

2021-07-26 22:18 UTC, kazu-taka commented on README.md
> +    CONSTRAINT fk_matching_1_id
@miu-ikeuchi 
fk_matching_1_idやfk_matching_2_idだと分かりにくいので、fk_like_users_matchingやfk_ messages_matchingとかの方がいいと思います✨

2021-07-26 22:18 UTC, kazu-taka commented on README.md
> +    send_id INT NOT NULL,
@miu-ikeuchi 
send_idだと分かりにくいので、user_idの方がいいと思います！

2021-07-26 22:18 UTC, kazu-taka commented on README.md
> +INSERT INTO prefectures(id, name) VALUES(11,'埼玉県');
@miu-ikeuchi 
この書き方でも問題ないですが、まとめて1つのINSERTで書くこともできるので共有します！！
http://raining.bear-life.com/mysql-2/insert%E3%81%A7%E8%A4%87%E6%95%B0%E8%A1%8C%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

2021-07-27 12:12 UTC, kazu-taka requested changes
@miu-ikeuchi 
1箇所微修正お願いします！
修正が終わったらマージしてOKです✨

2021-07-27 12:12 UTC, kazu-taka commented on README.md
> +GRANT ALL ON nyapple.* TO users;
@miu-ikeuchi 
ユーザー名変更したので、こちらも`TO nyapple_user`に修正お願いします！

2021-07-27 12:52 UTC, miu-ikeuchi commented
#1

2021-07-27 12:52 UTC, closed without merging